name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6.11
        php_version: 8.0
        php_extensions: "filter ftp gd gettext hash iconv json libxml mbstring openssl pcntl pcre PDO pdo_sqlite Phar posix readline Reflection session shmop SimpleXML sockets sodium SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer xml xmlreader xmlrpc xmlwriter xsl zip zlib"
        configuration: phpunit.xml
        coverage_cobertura: coverage/cobertura.xml
