name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6
        configuration: test/phpunit.xml
        php_extensions: "sqlite3 xml zip gd mbstring"
