name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6.11
        php_version: 8.0
        php_extensions: "gd mbstring openssl PDO pdo_sqlite sqlite3 xml xsl zip curl"
        configuration: phpunit.xml
        coverage_cobertura: coverage/cobertura.xml
